import { useState } from 'react';
import { Download } from 'lucide-react';
import type { ExportFormat, ExportOptions } from '../infrastructure/exports';
import type { CodeTarget } from '../domain/codegen';
import type { GenerationManifest } from '../domain/types';
import type { WorkerAction } from '../workers/protocol';
import { useText } from './preferences';

export function ExportPanel({ count, busy, manifest, datasets, run }: { count: number; busy: boolean; manifest?: GenerationManifest; datasets: { name: string; count: number }[]; run(action: WorkerAction): void }) {
  const t = useText();
  const [format, setFormat] = useState<ExportFormat>('json');
  const [options, setOptions] = useState<ExportOptions>({ dialect: 'sqlite', table: 'test_data', separator: ',', rawFormulas: false });
  const [selectedDataset, setSelectedDataset] = useState('');
  const [target, setTarget] = useState<CodeTarget>('playwright');
  const dataset = datasets.some(item => item.name === selectedDataset) ? selectedDataset : datasets[0]?.name;
  return <section className="panel export-panel"><div className="panel-heading"><div><span className="eyebrow">{t('DELIVERY', 'EKSPORT')}</span><h2>{t('Ready for your test suite', 'Gotowe do testów')}</h2></div><Download size={20} /></div><div className="export-row"><label>{t('File format', 'Format pliku')}<select value={format} onChange={event => setFormat(event.target.value as ExportFormat)}>{['json', 'jsonl', 'csv', 'xml', 'yaml', 'xlsx', 'sql'].map(value => <option key={value} value={value}>{value.toUpperCase()}</option>)}</select></label>{datasets.length > 0 && <label>{t('Dataset', 'Zbiór')}<select value={dataset} onChange={event => setSelectedDataset(event.target.value)}>{datasets.map(item => <option key={item.name} value={item.name}>{item.name} ({item.count})</option>)}</select></label>}<button className="primary" disabled={!count || busy} onClick={() => run({ type: 'export', format, options, ...(dataset ? { dataset } : {}) })}><Download size={15} />{t('Export full result', 'Eksportuj cały wynik')}</button></div>
    {format === 'csv' && <div className="export-options"><label>{t('Separator', 'Separator')}<select value={options.separator} onChange={event => setOptions({ ...options, separator: event.target.value })}><option value=",">Comma</option><option value=";">Semicolon</option><option value={'\t'}>Tab</option><option value="|">Pipe</option></select></label><label className="checkbox"><input type="checkbox" checked={Boolean(options.bom)} onChange={event => setOptions({ ...options, bom: event.target.checked })} />UTF-8 BOM</label><label className="checkbox"><input type="checkbox" checked={Boolean(options.rawFormulas)} onChange={event => { if (!event.target.checked || window.confirm(t('Raw CSV may execute formulas in spreadsheet software. Enable only for controlled tests?', 'Surowy CSV może wykonywać formuły w arkuszu. Włączyć do kontrolowanych testów?'))) setOptions({ ...options, rawFormulas: event.target.checked }); }} />{t('Raw formula samples', 'Surowe próbki formuł')}</label></div>}
    {format === 'sql' && <div className="form-grid"><label>{t('Dialect', 'Dialekt')}<select value={options.dialect} onChange={event => setOptions({ ...options, dialect: event.target.value as ExportOptions['dialect'] })}><option value="sqlite">SQLite</option><option value="postgresql">PostgreSQL</option><option value="mysql">MySQL</option></select></label><label>{t('Table name', 'Nazwa tabeli')}<input value={options.table} onChange={event => setOptions({ ...options, table: event.target.value })} /></label></div>}
    <p className="muted">{t('Nested objects become JSON strings in CSV, XLSX and SQL. XML preserves types in value elements.', 'Obiekty zagnieżdżone są tekstem JSON w CSV, XLSX i SQL. XML zachowuje typy w elementach value.')}</p><details><summary>{t('Automation code & replay manifest', 'Kod automatyzacji i manifest odtworzenia')}</summary><div className="export-row"><label>{t('Code target', 'Format kodu')}<select value={target} onChange={event => setTarget(event.target.value as CodeTarget)}><option value="playwright">Playwright fixture</option><option value="cypress">Cypress fixture JSON</option><option value="typescript">TypeScript interface</option><option value="java">Java builder</option><option value="rest-assured">REST Assured payload</option></select></label><button disabled={!count || busy} onClick={() => run({ type: 'code', target })}>{t('Download code', 'Pobierz kod')}</button></div><button disabled={!manifest || busy} onClick={() => run({ type: 'manifest' })}>{t('Download replay manifest', 'Pobierz manifest odtworzenia')}</button>{manifest && <p className="muted"><code>{manifest.engine}</code> · {manifest.seed} · {manifest.referenceDate}</p>}</details>
  </section>;
}
